#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CCBBAndroid.Resource", IsApplication=true)]

namespace CCBBAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int an = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bn = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btnboom = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btnboomboom = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ccbb1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ccbb2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ccbb3 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ccbb4 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int cn = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int coco_fechar_video = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int coco_play = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int coco_play_video = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int coco_stop = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int cocofecharvideo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int cocoplay = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int cocoplayvideo = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int cocostop = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int coqueiro_cocos = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int dn = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int en = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int fn = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int gn = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int hn = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_launcher = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Icon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int imgceu = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int imgchao = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int In = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int jn = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int kn = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ln = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int mn = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int nn = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int on = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int pn = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int qn = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int rn = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int sn = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int tn = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int un = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int vn = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int wn = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int xn = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int yn = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int zn = 2130837549;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int ceu = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int chao = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int chickaChickaButton = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int coqueiro = 2131230723;
			
			// aapt resource value: 0x7f080009
			public const int image = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int layoutPrincipal = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int playMusicaButton = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int playVideoButton = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int videoMusicaSpinner = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int videoPlayer = 2131230728;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int row = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int ccbb1 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ccbb2 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ccbb3 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ccbb4 = 2130968579;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int action_settings = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
